# Configuration de la base de donn√©es MySQL/MariaDB
database:
  host: "localhost"
  port: 3306
  database: "attention"
  username: "jsp"
  password: "changeme"
  ssl-mode: "DISABLED"
  timezone: "UTC"